# Site
repository: youngjun-99/youngjun-99.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 노영준
title: NLP Researcher
email: nyj5979@naver.com
website: https://youngjun-99.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  youngjun-99
linkedin_username: 노영준

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  2년 차 개발자로 스타트업에서 메일링 서비스를 개발/운영한 경험이 있습니다. 자동 메일링 서비스를 담당했으며, 필요에 따라 크롤러, 웹 개발 역할을 겸하였습니다. 더나눔협동조합의 첫 번째
              개발자로 입사하여 입주 광고 업체 입점을 20건 유치하면서 회사에 필요한 모든 기술 역량을 책임졌던 경험이 있습니다.
            
            가치 창출에 기여하는 것을 좋아합니다. 이를 위해 빠르게 개발하고 배포하는 것은 물론, 개발 후에 지속적으로 리팩토링하며 코드 확장성을 높이는 작업을 하고자 노력해왔습니다. 특히, 재사용
              가능성이 높은 코드는 모듈화하여 사내 라이브러리로 만들며 다른 개발자와 커뮤니케이션하며 협업해왔습니다.
            
            새로운 경험에 뛰어드는 것을 좋아합니다. 기존에 자동화, 프론트앤드, 백엔드 업무를 담당했었다면, TmaxAI에서 자연어 처리와 머신러닝을 공부하며 업무에 기여하고자 노력하였습니다. 입사
              3개월 수습 기간동안, 외부 과제 3년 치를 3개월 만에 완벽히 수행하여 TTA 인증을 받은 경험이 있습니다.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TmaxAI
        link: www.tmax.co.kr/tmaxai
        # link_text: boringcompany.com
        sub_title: 연구원
        caption: 2022.06 ~ 현재
        quote: >
          초개인화 지식 케어 서비스 개발 및 정부 과제
        description: | # this will include new lines to allow paragraphs
              -KEIT 과제 3년치 과제 3개월동안 해결
              -회사 서비스 백엔드 서버 개발
              -사내 머신러닝 스터디 진행
              -코드리뷰 & 코드 리팩터링
              -재사용 가능 코드 모듈화

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: KLUE_RoBERTaGCN
        link: github.com/payitfoward/klue_robertagcn
        # link_text: Project Website
        additional_links:
          - title:  payitfoward/klue_robertagcn
            icon: fab fa-github
            url: github.com/payitfoward/klue_robertagcn
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          KLUE 데이터셋 SOTA 달성
        description: | # this will include new lines to allow paragraphs
          언어 임베딩 모델 <mark>RoBERTa와 Graph Convolution Network를 활용해 KLUE-ynat(Topic Classification)에서 SOTA달성

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Front-end
        quote: >
          Front-end
        description: | # this will include new lines to allow paragraphs
              -Java
              -HTML/CSS
              -Bootstrap

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
